// Persona Lab Type Definitions
// Contains only frontend-specific types not generated by Orval

// ============================================
// Graph Display Types (Frontend-specific)
// ============================================

/** Layer in the persona graph (0 = center, 3 = outermost) */
export type GraphNodeLayer = 0 | 1 | 2 | 3;

/** Node types in the graph-based system */
export type GraphNodeType =
	| "profile_summary" // Layer 0 - Overall profile with archetype
	| "essay_angle" // Layer 1 - Patterns/themes
	| "key_story" // Layer 2 - Complete narratives with STAR
	| "detail"; // Layer 3 - Specific achievements, evidence

/** Connection edge types (normal relationships) */
export type ConnectionEdgeLabel =
	| "enables"
	| "builds_on"
	| "supports"
	| "complements";

/** Tension edge types (contradictions - valuable for essays) */
export type TensionEdgeLabel =
	| "contradicts"
	| "evolved_from"
	| "challenged_by"
	| "transformed";

/** All edge labels */
export type GraphEdgeLabel = ConnectionEdgeLabel | TensionEdgeLabel;

/** Edge category for styling purposes */
export type GraphEdgeType = "connection" | "tension";
