import type { ProgramDetailResponse } from "@/lib/api/types";

export const MOCK_PROGRAM_DETAIL: ProgramDetailResponse = {
	id: "1",
	universityId: "mit",
	universityName: "Massachusetts Institute of Technology",
	universityCountry: "United States",
	universityCity: "Cambridge, MA",
	universityLogoUrl: "/universities/mit.png",
	universityWebsiteUrl: "https://www.mit.edu",
	universityDescription:
		"The Massachusetts Institute of Technology is a private research university in Cambridge, Massachusetts. Founded in 1861, MIT has played a significant role in the development of many areas of modern technology and science.",
	rankingQs: 1,
	rankingTimes: 5,
	rankingNational: 2,
	programName: "Master of Science in Computer Science",
	programDescription:
		"The Master of Science in Computer Science (MSCS) program at MIT is designed to prepare students for leadership roles in the computing industry and academia. Students work closely with world-renowned faculty on cutting-edge research in areas including artificial intelligence, systems, theory, and graphics.",
	degreeType: "Master",
	degreeName: "MS",
	majorCategories: ["Computer Science", "Technology", "Artificial Intelligence"],
	durationMonths: 24,
	deliveryMode: "On Campus",
	language: "English",
	programUrl: "https://www.eecs.mit.edu/academics/graduate-programs/",
	admissionsUrl: "https://gradapply.mit.edu/eecs/apply/",
	tuitionAnnualUsd: 58240,
	tuition: {
		annualUsd: 58240,
		totalUsd: 116480,
		notes: "Tuition covers two academic years. Additional fees may apply.",
	},
	applicationFeeUsd: 75,
	scholarshipAvailable: true,
	ieltsMinimum: 7.5,
	toeflMinimum: 100,
	requirements: {
		gpaMinimum: 3.7,
		gpaScale: 4.0,
		ieltsMinimum: 7.5,
		toeflMinimum: 100,
		greRequired: true,
		gmatRequired: false,
		workExperienceYears: 0,
		documents: [
			"Official Transcripts",
			"GRE Scores",
			"IELTS/TOEFL Scores",
			"3 Letters of Recommendation",
			"Statement of Purpose",
			"Resume/CV",
			"Research Statement (optional)",
		],
		notes:
			"Strong research experience and publications are highly valued but not required.",
	},
	intakes: [
		{
			id: "fall-2025",
			season: "2025",
			seasonDisplay: "Fall",
			applicationStartDate: "2024-09-15",
			earlyDeadline: "2024-11-15",
			applicationDeadline: "2025-01-10",
			startDate: "2025-09-01",
			isActive: true,
		},
		{
			id: "fall-2026",
			season: "2026",
			seasonDisplay: "Fall",
			applicationStartDate: "2025-09-15",
			earlyDeadline: "2025-11-15",
			applicationDeadline: "2026-01-10",
			startDate: "2026-09-01",
			isActive: false,
		},
	],
	nextDeadline: "2025-01-10",
	nextIntake: "Fall 2025",
	fitScore: 67,
	fitCategory: "target",
	fitReasons: [
		"Your GPA (3.6) meets the minimum requirement (3.5)",
		"Perfect field alignment in Computer Science",
		"Your IELTS score (7.0) meets the minimum requirement",
		"Strong research experience in AI aligns with faculty interests",
	],
	fitGaps: [
		"Tuition ($58K/yr) is above your stated budget ($35K/yr) → Look for assistantships or external scholarships",
		"GPA (3.6) is slightly below the average admitted student GPA (3.8) → Emphasize strong final-year performance and research",
		"GRE scores recommended but not submitted → Consider taking the GRE to strengthen application",
	],
	isSaved: true,
};
